Repository EESSI/software-layer-scripts, pull requests merged in 2025-09, with the labels that each got.

#77 Avoid error when unloading EasyBuild module
  EESSI-extend-easybuild.eb
Labels: bug, bot:deploy

#90 check EB version when checking if `terse` build option is used
  eb_hooks.py
Labels: bot:deploy

#87 Update LAMMPS pre-configure hook to disable SIMD for ARM + CUDA
  eb_hooks.py
Labels: 2023.06-software.eessi.io, bot:deploy

#95 add pre-configure hook for GRASS that replaces paths of filtered dependencies
  eb_hooks.py
Labels: bot:deploy
