Repository EESSI/software-layer-scripts, pull requests merged in 2025-08, with the labels that each got.

#45 Add settings for EasyBuild 5+ to EESSI-extend
  .github/workflows/tests_eessi_extend_module.yml
  EESSI-extend-easybuild.eb
Labels: 2025.06-software.eessi.io

#54 fix typo in `EESSI-extend` + install CUDA in host injections earlier in the software install scripts (+ deploy `EESSI-extend/2025.06`)
  EESSI-extend-easybuild.eb
  EESSI-install-software.sh
Labels: 2025.06-software.eessi.io, 2023.06-software.eessi.io, bot:deploy

#67 fix condition in EESSI-extend + fix tarball naming for CPU-only tarballs
  EESSI-extend-easybuild.eb
  EESSI-install-software.sh
  bot/build.sh
Labels: bug, 2025.06-software.eessi.io, 2023.06-software.eessi.io, bot:deploy

#59 Adapt subdir for CUDA toolkit in host injections
  EESSI-install-software.sh
  create_lmodsitepackage.py
  easystacks/README.md
  easystacks/software.eessi.io/2023.06/accel/nvidia/rebuilds/20250807-eb-5.1.1-CUDA-cuDNN-new-host-injections-dir.yml
  eb_hooks.py
  scripts/gpu_support/nvidia/install_cuda_and_libraries.sh
  scripts/gpu_support/nvidia/install_cuda_host_injections.sh
Labels: bot:deploy

#72 Update one more dir to reflect the new location of CUDA installations in host_injections
  EESSI-install-software.sh
  scripts/gpu_support/nvidia/install_cuda_and_libraries.sh
Labels: bot:deploy

#71 fix limiting parallelism based on available cores in post-ready hook
  eb_hooks.py
Labels: 2025.06-software.eessi.io, 2023.06-software.eessi.io, bot:deploy

#73 Fix host injection path that was still pointing to .../versions/... instead of .../host_injections/...
  create_lmodsitepackage.py
Labels: bug, bot:deploy
